app:
  message: message succesfuly sent
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    routingkey: user.routingkey
    exchange2: user.exchange2
    routingkey2: user.routingkey2
server:
  port: 8081
